version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: always
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
