init:
	docker-compose exec web sh -c 'npx create-react-app my-app'
run:
	docker-compose exec web sh -c 'cd my-app && npm run start'
state-hook:
	docker-compose exec web sh -c 'cd react-hook/state-hook && npm i && npm run start'
effect-hook:
	docker-compose exec web sh -c 'cd react-hook/effect-hook && npm i && npm run start'