init:
	docker-compose exec web sh -c 'npx create-react-app my-app'
run:
	docker-compose exec web sh -c 'cd my-app && npm run start'
state-hook:
	docker-compose exec web sh -c 'cd react-hook/state-hook && npm i && npm run start'
effect-hook:
	docker-compose exec web sh -c 'cd react-hook/effect-hook && npm i && npm run start'
context-hook:
	docker-compose exec web sh -c 'cd react-hook/context-hook && npm i && npm run start'
reducer-hook:
	docker-compose exec web sh -c 'cd react-hook/reducer-hook && npm i && npm run start'
callback-hook:
	docker-compose exec web sh -c 'cd react-hook/callback-hook && npm i && npm run start'
memo-hook:
	docker-compose exec web sh -c 'cd react-hook/memo-hook && npm i && npm run start'
ref-hook:
	docker-compose exec web sh -c 'cd react-hook/ref-hook && npm i && npm run start'